<h1>Bienvenu sur recetteRevolution</h1>
<p>RecetteRevolution est la dernière version de l'application programmer par "erdnaxe" qui permet de gérer et de trier ses recettes.<br/>
Elle est totalement programmé en html, css3 et php4.</p>
<div class="table">
<?php
	echo '<a href="'.Atomik::url('editeur').'"><div class="fastAdd">Ajouter une recette</div></a>';
	echo '<a href="'.Atomik::url('import').'"><div class="fastImp">Importer une recette</div></a><br/>';
	echo '<a href="'.Atomik::url('TBimp').'"><div class="fastTB">Imprimer la table des matières</div></a>';
?>
</div>