<div class="jumbotron">
    <h1>Bienvenue !</h1>
    <p>Bienvenue sur l'application de gestion de recettes développée par erdnaxe.</p>
    <p>Grâce à cette application, vous pouvez tapez ou importer vos recettes pour ensuite les mettre en forme.</p>
    <p>
        Vous pouvez importer actuellement que du texte copier / coller. La fonction d'importation word vers RecetteInLine n'est pas encore fonctionnelle.
        L'application gère actuellement l'export en format <em>.pdf</em> ainsi d'une prévisualisation sur le site en <em>html5</em>.
    </p>
    <p><a href="<?php echo Atomik::url('explorer'); ?>" class="btn btn-primary btn-lg" role="button">Commencer à explorer les recettes</a></p>
</div>