<h1>Bienvenu sur l'accueil de Recette en ligne !</h1>
<p>Recette en ligne permet de g&eacute;rer et de trier ses recettes.<br/>
Elle est totalement programm&eacute; en html, css3 et php4 et n'utilise pas une base de donn&eacute;es.</p>
<div class="table">
<?php
echo '<a href="'.Atomik::url('editeur').'"><div class="fastAdd">Ajouter une recette</div></a>';
echo '<a href="'.Atomik::url('import').'"><div class="fastImp">Importer une recette</div></a><br/>';
echo '<a href="'.Atomik::url('TBimp').'"><div class="fastTB">Imprimer la table des mati&egrave;res</div></a>';
?>
</div>